### ISSUE TITLE
[Feature Request] Status Updated For Device

### ISSUE THREAD

**Issue by monsieurlatte** [ollo69/ha-smartthinq-sensors#129]
**Is your feature request related to a problem? Please describe.**
Not a problem, on the old Smarthinqs integration the status for the device updates based on the status, IE, washing, rinsing, drying, night drying etc.  Whereas this one is either off or on.

**Describe the solution you'd like**
Any chance you could do the same?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ollo69** [comment]
There is a sensor attribute to get this information, and if you need you can use `platform_template` to create a dedicated sensor with this value.

**Comment by monsieurlatte** [comment]
I see, I'm glad you make it sound so easy :D , there is zero chance I'll be able to figure that out.  I can't even get my fan template to work after all the changes they made.  Thanks for the info though!

**Comment by ollo69** [comment]
Somenthing like this in your `configuration.yaml`:

```
sensor:
  - platform: template
    
    sensors:
        
      washer_current_run_state:
        friendly_name: 'Whasher Phase'
        icon_template: mdi:washing-machine
        value_template: "{{ state_attr('sensor.washer', 'run_state') }}"
 ```

Replace `sensor.washer` with your sensor name, really not so complex 😉

Did you check [fan documentation](https://www.home-assistant.io/integrations/fan/) to find out what you have to change.
