### ISSUE TITLE
Howto for notifications

### ISSUE THREAD

**Issue by Golab** [ollo69/ha-smartthinq-sensors#13]
Hello can you please make a howto showing how to make push notification when washing/dryer machine is finished it sends out a notification to all devices like a iPhone

And also a howto so when it is finished it sends a command to my speakers to say washing machine is now finessed 

Make the howto so it’s made for beginners

**Comment by geekofweek** [comment]
This would probably be a better suited question for the [Home Assistant forum](https://community.home-assistant.io) as it really doesn't pertain to the integration as it only adds the devices into Home Assistant.  Automations like that will work the same way with various devices and are not unique to this.

That said I have examples doing both.
[iOS Notification](https://github.com/geekofweek/homeassistant/blob/master/automation/laundry.yaml#L116)
[Audio TTS Notification](https://github.com/geekofweek/homeassistant/blob/master/automation/laundry.yaml#L289)

**Comment by Golab** [comment]
Where do I find all entity_id that my washing machine has?

I can only find sensor.tvattmaskin

**Comment by geekofweek** [comment]
Should show up under the integrations page once setup, if you click into it should show you.

**Comment by ollo69** [comment]
@geekofweek, 

thanks for support.

As he suggested, this would probably be a better suited question for the [Home Assistant forum](https://community.home-assistant.io/).

**Comment by pigmos** [comment]
I wrote this automation to send a message to my google home when washer finished:

```
- id: '1585634580636'
  alias: Lavatrice_Fine
  description: Alert when washer finishes
  trigger:
  - entity_id: sensor.MyWasher
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Washer finished
    entity_id: media_player.MyGoogleHome
    service: tts.google_say
```

You have to modify Entity names.

**Comment by towerhand** [comment]
I'm creating a template sensor to use as a trigger in the automations. Haven't tested it yet though.
 
```
- platform: template
  sensors:
    washer_run_completed:
      value_template: "{{ states.sensor.washer.attributes.run_completed }}"
      friendly_name: Washer Cycle Completed
      icon_template: 'mdi:check'
```
