### ISSUE TITLE
[BUG] Latest version adds/removes attributes to the refrgerator entity

### ISSUE THREAD

**Issue by RealGandy** [ollo69/ha-smartthinq-sensors#260]
**Describe the bug**

Latest version appears to add and then remove the attribute assumed_state: from the <b>binary_sensor.refrigerator_door_open</b> entity. This plays havoc with automations that are set to trigger on the state change from closed to open and vice-versa as this seems to cause the automation to trigger whenever this attribute is updated

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

Automation should only trigger on state chnage, but the adding and removing of this atribute from the entity causes issues

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): core - supervised
 - Home Assistant version installed: 2021.12.8
 - Component version installed: v0.11.0
 - Last know working version: 0.10.7
 - LG device type and model with issue: Refrigerator GSJ961PZVV
 - LG devices connected (list): just above

**Output of HA logs**
Paste the relavant output of the HA log here.

This is the <b>changed variables</b> output from the triggered automation, showing that the attribute assumed_state: appears in the to_state abut not in the from_state. It does NOT show up when looking at the entity in Dev Tools, and appears to be delted very quickly afterwards, as my automation gets triggered again within a minute.

```
Executed: January 6, 2022, 4:00:26 PM
this:
  entity_id: automation.fridge_door
  state: 'on'
  attributes:
    last_triggered: '2022-01-06T15:00:25.882876+00:00'
    mode: single
    current: 0
    id: '1623425099154'
    friendly_name: Fridge Door
  last_changed: '2022-01-05T10:11:28.912403+00:00'
  last_updated: '2022-01-06T15:00:26.684917+00:00'
  context:
    id: cf381407a2720c4481035a8d51a0ddac
    parent_id: 175326afd80a4c7b20582c7a4c34f0e8
    user_id: null
trigger:
  id: '0'
  idx: '0'
  platform: state
  entity_id: binary_sensor.refrigerator_door_open
  from_state:
    entity_id: binary_sensor.refrigerator_door_open
    state: 'off'
    attributes:
      device_class: opening
      friendly_name: Refrigerator Door open
    last_changed: '2022-01-06T14:20:51.454453+00:00'
    last_updated: '2022-01-06T15:00:25.868900+00:00'
    context:
      id: 175326afd80a4c7b20582c7a4c34f0e8
      parent_id: null
      user_id: null
  to_state:
    entity_id: binary_sensor.refrigerator_door_open
    state: 'off'
    attributes:
      assumed_state: true
      device_class: opening
      friendly_name: Refrigerator Door open
    last_changed: '2022-01-06T14:20:51.454453+00:00'
    last_updated: '2022-01-06T16:00:26.305954+00:00'
    context:
      id: b5a5807f8ec711c4c173fc3130b1a757
      parent_id: null
      user_id: null
  for: null
  attribute: null
  description: state of binary_sensor.refrigerator_door_open
```
![image](https://user-images.githubusercontent.com/305484/148420302-1fe4f62a-94d0-436f-86fd-441dc80faa22.png)
Image showing no assumed_state: attribute

**Additional context**
