### ISSUE TITLE
Energy Current with wrong values

### ISSUE THREAD

**Issue by Diegaco2005** [ollo69/ha-smartthinq-sensors#302]
I've two air conditioners on my house, but using the sensor Energy Current, my devices reports values too differents. One of this has 12000 BTU, and the integration reports 50w in Energy Current on standby mode, while the 18000 BTU shows only 5w in the same sensor.
In case of my 12000 BTU unit, it's label reports a 3.51w to the idle consuption. How I can update the correct idle consuption on the idle energy sensor?
![image](https://user-images.githubusercontent.com/32584093/159592266-c539cdd9-18a6-41db-9f7a-db22955d0634.png)

**Comment by Xitro01** [comment]
I have issues with power readings as well. Turned it on and it went from 0W to 50W. Then turned it off and suddenly went to 56W? If it's on I expect something around 400-600W, and when it's off I expect something around 3W.

**Comment by Tymose** [comment]
Same issue hereon DC18RQ NSK unit. Seems to be showing 50W constantly when turned off. Keeps showing like that after I've turned it on first time with integration enabled. Before first turning on it was showing 0W.

**Comment by ollo69** [comment]
Please attach device diagnostics while your device is idle so that I can check the value in payload,

**Comment by Xitro01** [comment]
> Please attach device diagnostics while your device is idle so that I can check the value in payload,

[smartthinq_sensors-841bdbf7cdcba74f0490298a2e010220-Airconditioner-50b9fa0937b72643ace0be6c2f022be1.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10444602/smartthinq_sensors-841bdbf7cdcba74f0490298a2e010220-Airconditioner-50b9fa0937b72643ace0be6c2f022be1.json.txt)

**Comment by Xitro01** [comment]
For those looking for a work-around/temporarily fix:
```
template:
  - sensor:
      - name: "Airconditioner Energy current fixed"
        unique_id: airconditioner_energy_current_fixed
        unit_of_measurement: "W"
        state: >
          {% if is_state('sensor.airconditioner_energy_current', '50') %}
            3.5
          {% else %}
            {{ states('sensor.airconditioner_energy_current') }}
          {% endif %}

sensor:
  - platform: integration
    name: Airconditioner
    unique_id: sensor.airconditioner_energy
    source: sensor.airconditioner_energy_current_fixed
    unit_prefix: k
    method: left
```
