### ISSUE TITLE
Cannot set fan_mode on scenes

### ISSUE THREAD

**Issue by dgspai** [ollo69/ha-smartthinq-sensors#307]
**Describe the bug**
I can set temperature, swing_mode, state and fan_mode though the HA interface, but the fan_mode is not set when using scenes.

A example scene:
```
- name: My Temp Scene
  entities:
    climate.ar_condicionado:
      temperature: 22.5 # OK
      fan_mode: NATURE # NOT OK
      swing_mode: VerticalSwing # OK
      state: cool # OK
```

[Device Info](https://pastebin.com/VT6mZeMf)

**Expected behavior**
It should be possible to set fan_mode on HA scenes

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed:  2022.4.4
 - Component version installed: v0.12.12
 - Last know working version: NA
 - LG device type and model with issue: LG AC RAC_056905_WW
 - LG devices connected (list): Single device

**Output of HA logs**
No relevant output of the HA log.

**Additional context**
I can provide more info if needed.

**Comment by dgspai** [comment]
I found a workaround for anyone with same problem.
Instead of using scenes, you can use scripts to set the fan_mode:

```
set_ac_to_eco:
  alias: Set AC to Eco mode
  sequence:
  - service: climate.set_fan_mode
    data:
      fan_mode: LOW
    target:
      device_id: *REDACTED*
  mode: single
  icon: mdi:speedometer-slow
```
