### ISSUE TITLE
Invalid swing_mode

### ISSUE THREAD

**Issue by SebastiaanBij** [ollo69/ha-smartthinq-sensors#356]
Hello,

I have been working on a script (HA script) to set the swing mode of my LG ThinQ HVAC. For this I use the `climate.set_swing_mode` service. The YAML file looks as follows:
```yaml
alias: Example
sequence:
  - service: climate.set_swing_mode
    data:
      swing_mode: "Horizontal Center"
    target:
      entity_id: climate.air_conditioning_air_care
mode: single
icon: mdi:bed-empty
```

In order to get to this point, I looked through the code to determine what the value should be of the `swing_mode` data parameter. This is what I could make out of the code. However the problem is that once I try to run this script, I receive the following error message: `Invalid swing_mode [Horizontal Center]`.

Now I don't really know what the problem is, and my apologies in advance if this is a stupid question. But is this a mistake on my part (and if so, what would be the solution) or is there something else going on?
