### ISSUE TITLE
How to use the binary_sensor.lavatrice_wash_completed 

### ISSUE THREAD

**Issue by gerasimone** [ollo69/ha-smartthinq-sensors#39]
Hi,
I have an automation in my setup that listen for changes of the binary_sensor.lavatrice_wash_completed, but seems this never happens. 
Also in history, the state is never changed. 
The automation works, if i trigger manually the action is fired. 
Can you tell me how to catch the washing complete event correctly?
Thanks

**Comment by ollo69** [comment]
The sensor control the current values for previous-state and current-state. If the state of the sensor never change probably the check do not match the state of your washer. 
Please check what are the values for this 2 attributes when the wash is completed and write back here.

**Comment by gerasimone** [comment]
this is an extract of the sensor state:
`run_completed: 'off'
error_state: 'off'
error_message: '-'
run_state: '-'
pre_state: Select Course
current_course: '-'
spin_option_state: '-'
watertemp_option_state: '-'
drylevel_option_state: '-'
tubclean_count: '41'
remain_time: '0:00'
initial_time: '0:00'
reserve_time: '0:00'`

**Comment by ollo69** [comment]
You must check the state exactly when the cycle is completed, may be you can run the shortest available cycle to make a test.

**Comment by gerasimone** [comment]
Ok, this is the running state, 2 minutes to the end:

> run_completed: 'off'
error_state: 'off'
error_message: Normal
run_state: Spinning
pre_state: Rinsing
current_course: Cotton
spin_option_state: 800 RPM
watertemp_option_state: '-'
drylevel_option_state: '-'
tubclean_count: '41'
remain_time: '0:02'
initial_time: '1:38'
reserve_time: '0:00'
doorlock_mode: 'On'
childlock_mode: 'Off'

And this is just a second after the washer shutdown itself for washing end

> run_completed: off
error_state: off
error_message: -
run_state: -
pre_state: Spinning
current_course: -
spin_option_state: -
watertemp_option_state: -
drylevel_option_state: -
tubclean_count: 41
remain_time: 0:00
initial_time: 0:00
reserve_time: 0:00
doorlock_mode: Off

thanks

**Comment by ollo69** [comment]
So it seems that your washer move from "Spinning" to off and do not provide the End State.
This is strange, and I don't know exactly how to manage, because the risk is to provide false "completed" message.
What is the model of your washer?

**Comment by gerasimone** [comment]
The model is F14U1JBS6, tha LG SmarthinQ app on my iphone give me the notification of washing complete, so i think probably LG get the notification just before the washing machine auto shutdown.
Probably to avoid false positive we should check the remain_time, initial_time and state change from on to off: 
when the state change from on with initial_time > 0:00 to off with remain_time = 0:00, the washing cycle is completed. what you thing about it?

**Comment by ollo69** [comment]
This is quite complex logic to implement with polled device, check may be missed. The End  status work perfectly because remain available in previous state and so the check is reliable. I don't know why your washer do not provide this. 

Please provide me the URL with the info of your washer (you can found this as a info log when HA start) so that I can check information that should be provided by your washer.

**Comment by gerasimone** [comment]
Ok i will try to find it! thanks

**Comment by snakuzzo** [comment]
HI @gerasimone ... here is my automation...
it works fine...in sync with LG app notification

```
- alias: LG Notifica fine lavaggio
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.lavatrice_wash_completed
    to: 'on'
  action:
  - data:
      message: Lavaggio terminato
      title: Lavatrice
    service: notify.telegram_diego
  - data:
      entity_id: media_player.googlehome4895
      volume_level: '0.6'
    service: media_player.volume_set
  - data:
      message: "lavatrice terminata"
      entity_id: media_player.googlehome4895
    service: tts.google_say
```
