### ISSUE TITLE
Washer/dryer unloading detection

### ISSUE THREAD

**Issue by TeoTN** [ollo69/ha-smartthinq-sensors#540]
One absolutely amazing thing would be if you could provide a sensor with either what's the load weight or whether doors are open. I would love to be able to setup a notification to remind me if I left the clothes in for too long after the cycle has finished.

**Comment by ollo69** [comment]
Attach diagnostics so that I can analyze information in payload.

**Comment by TeoTN** [comment]
Where do I start?

**Comment by crafty35a** [comment]
I'm also trying to figure out a way to determine if my LG washer/dryer/dishwasher have been unloaded, without luck so far. The washer/dishwasher do have "Door open" sensors with this integration, but they don't seem to function (they are always set to "open"). The dryer doesn't show a door sensor.

@ollo69, here are my diagnostics. Thanks!
[smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dishwasher-78d9e9a18b893bbbd17adb967a977d87.json](https://github.com/user-attachments/files/17210635/smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dishwasher-78d9e9a18b893bbbd17adb967a977d87.json)
[smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dryer-3058f0e3651aa008e882e6bfa76557f3.json](https://github.com/user-attachments/files/17210636/smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dryer-3058f0e3651aa008e882e6bfa76557f3.json)
[smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Washer-7e707696c82601a13712b456e40e7aeb.json](https://github.com/user-attachments/files/17210637/smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Washer-7e707696c82601a13712b456e40e7aeb.json)

**Comment by WisdomWolf** [comment]
I actually jumped through the hoops of setting up a Home Assistant dev container so that I could dig into this.  It looks like LG doesn't expose the door status for the washer or dryer.  Somewhat confusingly the payload does contain `"doorClose": "DOORCLOSE_OFF",`, but this value doesn't appear to ever change.  This makes sense though since their [official API documentation](https://thinq.developer.lge.com/en/cloud/docs/thinq-connect/device-profile/washer/#1) doesn't show anything about the door status (other than error status).  They do have door status for the [Refrigerator](https://thinq.developer.lge.com/en/cloud/docs/thinq-connect/device-profile/refrigerator/#1) and [Dish Washer](https://thinq.developer.lge.com/en/cloud/docs/thinq-connect/device-profile/dish-washer/#1).  Seems like an odd oversight to not have it for the Washer or Dryer.

**Comment by TeoTN** [comment]
I've sent a request to LG support to add door status and (if possible) load detection. It may make sense for others who are interested to also send a request independently to signal boost

**Comment by AndrewDessin** [comment]
I've looked recently and it still wasn't in the API. I ended up writing two autos using the washer/dryer state which works quite well. Just detect when a wash cycle ends and a dryer cycle hasn't started, with a manual button to clear the state if you airdry the load.

**Comment by TRusselo** [comment]
I added a zigbee contact sensor to my washer door.

helper binary sesnor setup "Washer Empty", defaults on,
Automations:
cycle starts, shut off "washer Empty".
Washer door opens, and "cycle complete" is on, set "washer empty" on

also:
https://github.com/phrz/lg-washer-dryer-card/

and ....
```
template sensor

template:
- sensor:
  - default_entity_id: sensor.washer_door_lock
    name: Washer Door Lock
    state: '{{ state_attr(''sensor.washer'',''door_lock'') }}'

automation:
- id: '1668897523815'
  alias: Washer Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.washer_wash_completed
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: sensor.washer_status
    state: Running
  action:
  - service: notify.mobile_app_tristyn_s_flip5
    data:
      message: clear_notification
      data:
        tag: laundry
  - service: notify.mobile_app_tristyn_s_flip5
    data:
      message: Washer is done.
      title: Laundry
      data:
        tag: laundry
  mode: single
  initial_state: true

- id: '1670563378098'
  alias: Washer Running
  description: ''
  triggers:
  - entity_id:
    - sensor.washer_current_status
    from:
    - power_off
    trigger: state
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.washer_status
      state: Idle
    - condition: state
      entity_id: sensor.washer_status
      state: Complete
    - condition: state
      entity_id: sensor.washer_status
      state: unknown
  actions:
  - data:
      topic: house/washer/status
      payload: Running
      retain: true
    action: mqtt.publish
  initial_state: true

- id: '1670563508083'
  alias: Washer Complete
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.washer_wash_completed
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.washer_status
    state: Running
  action:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: Complete
      retain: true
  - service: mqtt.publish
    data:
      topic: house/washer/time_complete
      payload: '{{ now().timestamp() }}'
      retain: true
  initial_state: true

- id: '1670563546734'
  alias: Washer Emptied
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.washer_door_contact
    from: 'off'
    to: 'on'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: sensor.washer_status
    state: Complete
    enabled: true
  action:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: Idle
      retain: true
      qos: 0
  - service: mqtt.publish
    data:
      topic: house/washer/time_emptied
      payload: '{{ now().timestamp() }}'
      retain: true
  initial_state: true

- id: '1670564181814'
  alias: Washer Idle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.washer_power
    from: 'on'
    to: unavailable
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: Idle
      retain: true
  mode: single
  initial_state: true
```
