### ISSUE TITLE
Refrigerator Filter Sensors

### ISSUE THREAD

**Issue by shwarnock** [ollo69/ha-smartthinq-sensors#764]
My LG refrigerator has an air filter and water filter sensor that can let me know when they need to be replaced. These don't seem to be integrated into HA. I would love to have sensors for these two filters so I can run some automations when they need to be changed. Basically, send some phone notifications and add the filters to my shopping list.

**Comment by shwarnock** [comment]
Any traction on this? If there is anything I can do to help lmk

**Comment by Dilergore** [comment]
The _water filter used month_ is available under the refrigerator sensor:
<img width="305" alt="image" src="https://github.com/user-attachments/assets/bd91254b-e527-421c-bcdc-eac110aed4fe">

I do not have an air filter so cannot comment on that. The recommendation (in case of my fridge) is to change the filter every 6 months, so I have an automation to send a push message every day to my phone if the sensor value is >= 6.

**Comment by jbrockmancas** [comment]
My fridge has an air filter and currently has a value of `fresh_air_filter: Looks Good` I just replaced it so I'm not sure what the values are as time goes on.
![image](https://github.com/user-attachments/assets/813bbc6e-7199-4493-a56d-dc24926f6a61)

**Comment by SeanPM5** [comment]
This would be a helpful feature. I had to wait six months for the air filter to expire first before I could see the attribute values in order to automate it. Sharing the template binary sensors I made here:

```
template:
  - binary_sensor:

      - name: Fridge Air Filter
        device_class: problem
        unique_id: fridge_air_filter
        state: >-
          {{ is_state_attr('sensor.refrigerator', 'fresh_air_filter', 'Replace Filter') }}
        availability: >
          {{ states('sensor.refrigerator') not in ['unknown', 'unavailable', 'off'] }}


      - name: Fridge Water Filter
        device_class: problem
        unique_id: fridge_water_filter
        state: >-
          {{ state_attr('sensor.refrigerator', 'water_filter_used_month') | is_number and state_attr('sensor.refrigerator', 'water_filter_used_month') >= '6' }}
        availability: >
          {{ states('sensor.refrigerator') not in ['unknown', 'unavailable', 'off'] }}
```
